### ISSUE TITLE
Potlatch three interface freeze on Apple Silicon

### ISSUE THREAD

**Issue by OlneyMe** [systemed/potlatch3#44]
Downloaded Potlach 3 to give a a try - and on my M2 Pro, everything seems fine until I hit save, at which point the interface freezes and the login dialog does not appear (although it does let me carry on editing, no buttons work, so I have to abandon them).

Using Firefox to launch.

An otherwise identically configured (same OS, same Firefox version) 2018 Intel Mac mini works as expected. While screen sharing into my old machine is a workaround, it is hardly ideal (it has quite enough to do as a server).

I was not asked to grant any permissions and both machine have the T2 security chip doohickey, if that is relevant.

Get info says it is a universal app, so Rosetta not an issue I presume.

Firefox 116.0.2 64 bit - MacOS Ventura 13.5, 2023 Mac mini M2 Pro/ 2018 Mac mini (the Intel box that works as expected).

**Comment by systemed** [comment]
Thanks! It does work on my M2 weirdly but is slightly awkward. I think there’s a newer AIR web component that should fix the issue - I’m away from my dev machine at the moment but will investigate when I’m back.

**Comment by OlneyMe** [comment]
> Thanks! It does work on my M2 weirdly but is slightly awkward. I think there’s a newer AIR web component that should fix the issue - I’m away from my dev machine at the moment but will investigate when I’m back. 

Ta. Give me a nudge if you meed me to do any testing.

**Comment by OlneyMe** [comment]
> Thanks! It does work on my M2 weirdly but is slightly awkward. I think there’s a newer AIR web component that should fix the issue - I’m away from my dev machine at the moment but will investigate when I’m back.

Hi - any update on this?. The issue persists (have ruled out me using a non-admin account as the issue, and Firefox has updated so it is, I assume, not that).

**Comment by OlneyMe** [comment]
To be a completist, 3.1 has resolved this issue.
